### PR TITLE
initial commit to backend-server

### PR DESCRIPTION
**Pull request by zelbael**
back-end server set up

### CODE REVIEW

**Comment by Sth84478** [comment]
Hey Reiczel, 

Just a few comments.

- I can't seem to find the main application to run. 
   - There should be a something called like BugWarsApplication.java file in there.
- Will we be using Java 21? I believe other teams are using Java 17

**Comment by jrhurleycode** [comment]
yes I'm noticing this too.  I suggest 

1. start from scratch and re-run the Spring initializer so we're running with Java 17, which is what we used for TE.  Every other option you had is correct!
2.  set up pgAdmin for a database.  You can call it "bug_wars"
3.  create a App.java file and application.properties. You can copy the App.java file from the mod3 final project, but make sure to change some of the references in App.java file and the application.properties file so it connects to the bug_wars database.

These are easy fixes!  Should be able to do this in no time!

**Comment by zelbael** [comment]
hi everyone! thanks for your suggestions, it was super helpful! 
i went ahead and created:
- new server with java 17
- user controller, model, service, and repo
- database in called bugwarsDB

**Comment by jrhurleycode** [comment]
Works for me.  Server is starting up for me.

**Review by jrhurleycode — DISMISSED** [review]
Server is starting up and able to connect to database.

**Comment by Sth84478** [comment]
Looks good. I think github is still showing the env.properties file. I tried to remove the cached file by doing git rm --cached env.properties. Hopefully that works.

**Review by Sth84478 — CHANGES_REQUESTED** [review]
env.properties is still showing in github. git rm --cached env.properties should clear it out. I tried to push that through but not sure if it was successful. Once that is done and the file is no longer showing, should be good to push to dev.

**Comment by Sth84478** [comment]
I made some updates to try and get the front end to fetch api end points from the backend. Currently facing some CORS issues and not sure how to resolve it. Hopefully someone else can take a look too. I pushed the code to this branch and also did a PR for the front end to have what I have so far merged into dev for testing.

**Pull request closed without merging**
